import { NodeProps, updatePreferences } from '~/services';
import { ConversationStep, InstructionStep, NavigationStep } from '~/utils/flow/types';

function conversationStep(
  icon: string,
  output: string,
  nextId: string = '',
  action: (input: any) => Promise<any> = async () => {}
): ConversationStep {
  return { icon, output, action, nextId };
}

function instructionStep(icon: string, output: string): InstructionStep {
  return { icon, output };
}

export function navigationStep(
  id: string,
  value: string,
  start?: NodeProps,
  end?: NodeProps
): NavigationStep {
  return { id, value, start, end };
}

/**
 * Represents the set of conversation steps for the application's navigation flow.
 * Each key corresponds to a unique step in the conversation, mapping to a `ConversationStep` object.
 *
 * The flow includes:
 * - `start`: Initial prompt for destination input.
 * - `no_route`: Informs user when no valid route is found.
 * - `start_nav`: Indicates route calculation and navigation start.
 * - `config`: Language setup step, optionally switching to Spanish.
 * - `config_weather`: Weather preference configuration.
 * - `config_vibrate`: Haptic feedback configuration and completion of first-time setup.
 * - `fallback`: Handles unrecognized user input.
 *
 * Each step may include a prompt, an icon, a next step, and an optional handler for updating user preferences.
 */
export const flow: Record<string, ConversationStep> = {
  start: conversationStep(
    'signpost',
    "where are we headed?\nlet me know and i'll find the best route",
    'start_nav'
  ),
  no_route: conversationStep(
    'gps-not-fixed',
    'no valid route,\nplease choose a different destination',
    'start_nav'
  ),
  start_nav: conversationStep(
    'route',
    'calculating your route and starting navigation now',
    'navigate'
  ),
  config: conversationStep(
    'language',
    "let's set up the app,\nwould you like to switch to spanish?",
    'config_weather',
    (input) => updatePreferences({ spanish: input })
  ),
  config_weather: conversationStep(
    'cloud',
    'language set,\ndo you want to know the weather before navigating?',
    'config_vibrate',
    (input) => updatePreferences({ weather: input })
  ),
  config_vibrate: conversationStep(
    'vibration',
    'weather updates set,\nwould you like haptic feedback for alerts?',
    'start',
    (input) => updatePreferences({ vibration: input, isFirstTime: false })
  ),
  fallback: conversationStep(
    'question-mark',
    "sorry, i didn't catch that,\ncould you try saying it again?"
  ),
};

/**
 * A mapping of navigation instruction keys to their corresponding `InstructionStep` objects.
 *
 * Each key represents a specific navigation action or status (e.g., `left`, `right`, `u-turn`, `rain`), and maps to an `InstructionStep` that defines the icon and spoken instruction for that action.
 *
 * This object is used to provide user-friendly navigation instructions and status updates throughout the application.
 *
 * @remarks
 * The keys are strings describing navigation steps or environmental statuses, and the values are generated by the `instructionStep` function, which takes an icon name and a description.
 *
 * @example
 * ```typescript
 * const leftTurn = direction['left'];
 * // leftTurn.icon === 'turn-left'
 * // leftTurn.description === 'please, turn to the left'
 * ```
 */
export const direction: Record<string, InstructionStep> = {
  origin: instructionStep('home', 'starting from'),
  start: instructionStep('explore', 'going to'),
  left: instructionStep('turn-left', 'please, turn to the left'),
  right: instructionStep('turn-right', 'please, turn to the right'),
  'slight-left': instructionStep('turn-slight-left', 'turn slightly to the left'),
  'slight-right': instructionStep('turn-slight-right', 'turn slightly to the right'),
  'sharp-left': instructionStep('rotate-left', 'make a sharp left turn'),
  'sharp-right': instructionStep('rotate-right', 'make a sharp right turn'),
  'u-turn': instructionStep('u-turn-right', 'please, make a u-turn'),
  straight: instructionStep('arrow-upward', 'go straight'),
  reroute: instructionStep('auto-awesome', 'hold up, rerouting quickly'),
  rain: instructionStep('umbrella', 'rain chance of'),
  temperature: instructionStep('cloud', 'current temperature'),
  end: instructionStep('place', 'you have arrived to'),
};
