export const commonInputs: Record<string, string[]> = {
  config: [
    'configurar',
    'preferences',
    'setup',
    'ajustes',
    'config',
    'preferencias',
    'opciones',
    'options',
    'configuración',
    'configuration',
    'setup',
    'configuración del sistema',
    'system configuration',
  ],
  yes: [
    'yes',
    'sí',
    'yeah',
    'ok',
    'okay',
    'affirmative',
    'sure',
    'seguro',
    'yeah sure',
    'correcto',
    'por supuesto',
    'of course',
    'claro',
    'dale',
    'perfecto',
    'perfect',
    'exacto',
    'all right',
  ],
  no: [
    'no',
    'nope',
    'no way',
    'negative',
    'negativo',
    'no gracias',
    'no thanks',
    'nah',
    'nope',
    'nada',
    'ninguno',
    'de ninguna manera',
    'no quiero',
    'no quiero eso',
    'no es necesario',
  ],
};
